/**
 * Types for the unified pending images system
 *
 * Users can add images to their message from three sources:
 * 1. Upload - file selected from their computer (uploaded immediately)
 * 2. Asset - image selected from the asset library
 * 3. AI Generated - image generated by the AI that user wants to edit/reference
 *
 * All sources converge into a unified array of PendingImage objects
 */

export type PendingImageSource = "upload" | "asset" | "ai_generated";

export interface PendingImage {
  /** Unique ID of the image in S3 storage */
  imageId: string;
  /** CloudFront URL for displaying the image (access via signed cookies) */
  url: string;
  /** Source of the image */
  source: PendingImageSource;
  /** Display title for the image */
  title?: string;
  /** Whether this image is currently being uploaded (only for 'upload' source) */
  isUploading?: boolean;
  /** Temporary local URL for preview during upload (only for 'upload' source) */
  localPreviewUrl?: string;
  /** Original message index (only for 'ai_generated' source - for history tracking) */
  messageIndex?: number;
  /** Original part index within the message (only for 'ai_generated' source) */
  partIndex?: number;
  /** Variant ID if from a parallel variant (only for 'ai_generated' source) */
  variantId?: string;
}

/** Maximum number of images that can be added to a single message */
export const MAX_PENDING_IMAGES = 5;

/**
 * Check if more images can be added
 */
export function canAddImage(pendingImages: PendingImage[]): boolean {
  return pendingImages.length < MAX_PENDING_IMAGES;
}

/**
 * Check if any images are still uploading
 */
export function hasUploadingImages(pendingImages: PendingImage[]): boolean {
  return pendingImages.some((img) => img.isUploading);
}

/**
 * Get the count of images that are not uploading
 */
export function getReadyImageCount(pendingImages: PendingImage[]): number {
  return pendingImages.filter((img) => !img.isUploading).length;
}
